services:
  nginx:
    volumes:
      - ./.warden/nginx/available.d/application.conf:/etc/nginx/available.d/application.conf
#      - ./.warden/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: ./.warden/php
      target: php-fpm

    volumes:
      - "./.warden/php/supervisor:/etc/supervisord.d/"

  nuxt:
    build:
      context: ./nuxt
      dockerfile: ../.warden/nuxt/Dockerfile
      target: dev
#    ports:
#      - "3000:3000"
    volumes:
      - "./nuxt:/app"
    hostname: dzencode-nuxt
#    environment:
#      - NODE_ENV=development
#      - NUXT_PORT=3000
#      - NUXT_HOST=0.0.0.0
    networks:
      default: null