services:
  nginx:
    volumes:
      - ./.warden/nginx/available.d:/etc/nginx/available.d

  php-fpm:
    build:
      context: ./.warden/php
      target: php-fpm

    command: sudo /usr/bin/supervisord -n
    volumes:
      - "./.warden/php/supervisor:/etc/supervisord.d/"